// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'danger': string;
  'primary': string;
  'secondary': string;
}
declare const cssExports: CssExports;
export = cssExports;
